### ISSUE TITLE
Panes have no borders

### ISSUE THREAD

**Issue by jacob-israel-turner** [trevordmiller/nova-hyperterm#18]
Hyper default:
![screen shot 2016-10-10 at 11 15 17 am](https://cloud.githubusercontent.com/assets/8698364/19248432/44a0fb4c-8eed-11e6-9576-fbe327ab19b3.png)

Hyper - nova:
![screen shot 2016-10-10 at 11 13 41 am](https://cloud.githubusercontent.com/assets/8698364/19248438/494aaecc-8eed-11e6-882c-9c2fd675fe15.png)

**Comment by trevordmiller** [comment]
Thanks for the feedback! I agree. This is a brand new feature of Hyper that was created after the initial `nova-hyperterm` release. We need to first update to the "hyper" rename (https://github.com/trevordmiller/nova-hyperterm/issues/15) but this should be taken care of next. Feel free to submit a pull request [using the "CONTRIBUTING" guidelines](https://trevordmiller.github.io/nova); otherwise, I'll get to this :)

**Comment by trevordmiller** [comment]
Working. Unfortunately Hyper still doesn't update plugins automatically so you will need to `cd ~/.hyper_plugins && rm -rf node_modules && npm install` to get latest.
![image](https://cloud.githubusercontent.com/assets/5497885/19258332/35f42e6a-8f34-11e6-8d0b-c9688868a3da.png)

**Comment by jacob-israel-turner** [comment]
🎉  Thanks!  Looks like removing then re-adding `"nova-hyperterm"` to the plugins array did it.
