### ISSUE TITLE
Cursor color in hyperterm in vim

### ISSUE THREAD

**Issue by aharris88** [trevordmiller/nova-hyperterm#7]
I've installed the nova theme for Hyperterm, iTerm, and Neovim. In hyperterm, the cursor color is blue, but in iTerm the cursor color is white. Also, the highlight color in vim is blue. This becomes a problem in Hyperterm when I put my cursor on a word that's highlighted. You can see in the top image that the "a" in PlugUpgrade isn't visible and it's hard to tell where the cursor is.

Hyperterm:
![screen shot 2016-09-22 at 8 31 02 am](https://cloud.githubusercontent.com/assets/3266363/18752315/44127dce-809f-11e6-949f-06bfa7cf8dfd.png)

iTerm:
![screen shot 2016-09-22 at 8 31 26 am](https://cloud.githubusercontent.com/assets/3266363/18752328/49090924-809f-11e6-937b-e58738713da7.png)

**Comment by aharris88** [comment]
I just realized that the reason the cursor is white in iTerm is because I had "Smart Cursor Color" on. If I turn that off, it looks the same as Hyperterm. I'm not sure if this is something that should be fixed in the iTerm and Hyperterm scheme or in the vim scheme.

**Comment by trevordmiller** [comment]
@aharris88 Yeah, I've thought about this but decided the conflict of cursor color / highlights was worth having consistency with `cyan` always representing user state. Unfortunately, Vim has no control over the cursor - it is handled by your terminal emulator (HyperTerm or iTerm); I would prefer to keep the cursor colors as is for now and instead try to encourage HyperTerm to create a smart cursor mode like iTerm. Since HyperTerm is all just CSS, I have seen a few HyperTerm themes that use CSS `mix-blend-mode: difference` (like the [atom one dark theme](https://github.com/mdo/hyperterm-atom-dark/blob/master/index.js#L37)) but I haven't found a mix blend mode that looks decent to me as it creates "difference" colors that don't match the rest of the theme.

cc: @rauchg
